version: '3'

volumes:
  postgres_data: {}
  postgres_data_backups: {}
  static_volume: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: k8s_workshop_django
    volumes:
      - .:/app
      - static_volume:/app/k8s_workshop/static
    depends_on:
      - postgres
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    command: /start

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.envs/.postgres

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./compose/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/k8s_workshop/static
    depends_on:
      - django
