apiVersion: v1
data:
  DATABASE_URL: postgres://postgres:postgres_secret@postgres:5432/k8s_workshop
  POSTGRES_DB: k8s_workshop
  POSTGRES_HOST: postgres
  POSTGRES_PASSWORD: postgres_secret
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres_user
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: django-envs--postgres
  name: django-envs--postgres
