#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /code/manage.py collectstatic --noinput
python /code/manage.py migrate
/usr/local/bin/gunicorn k8s_workshop.wsgi --bind 0.0.0.0:5000 --chdir=/code